services:
  - type: web
    name: nhahangcayphuong2025-api
    env: node
    plan: free
    rootDir: backend   # <--- Quan trọng: chỉ rõ backend
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
